FROM ubuntu:latest

RUN apt-get update

RUN  apt-get install -y python3-pip

RUN  pip3 install --upgrade pip



RUN pip3 install numpy pandas matplotlib seaborn plotly sklearn




COPY diabetes.csv .

COPY test.py .

CMD ["python3","-u","test.py"]